# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dare2ask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='../static/images/default.png', upload_to='profile_images'),
        ),
    ]
