# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dare2ask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('upvotes', models.IntegerField(default=0)),
                ('answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='views',
        ),
        migrations.AddField(
            model_name='lecture',
            name='course_num',
            field=models.CharField(default=-1, max_length=128),
        ),
        migrations.AddField(
            model_name='lecture',
            name='join_ID',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='question',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dare2ask.Lecture'),
        ),
    ]
