# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dare2ask', '0002_auto_20190313_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lecturer',
            field=models.BooleanField(default=False),
        ),
    ]
