# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dare2ask', '0002_auto_20190306_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
