# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dare2ask', '0002_auto_20190306_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='title',
            new_name='name',
        ),
    ]
