# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dare2ask', '0003_userprofile_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_ID',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
