# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-09 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dare2ask', '0003_auto_20190308_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
