# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dare2ask', '0004_question_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user_ID',
        ),
    ]
