# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dare2ask', '0006_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='search',
            name='slug',
            field=models.SlugField(),
        ),
    ]
