# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dare2ask', '0007_auto_20190321_0050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
